dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - python -c "import sys; sys.exit(int(sys.version_info < (3, 2)));" || pip install future
  - pip install coveralls
script:
  - coverage run --source=gostop -m unittest discover tests
after_success:
  - coveralls
